<a href="https://colab.research.google.com/github/Bavesh-08/fake-news-prediction/blob/main/fake_news_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the dependencies

import numpy as np
import pandas as pd
import re      #regular expression
from nltk.corpus import stopwords    #natural laungage toolkit
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [ ]:
#downloding the stopwords

import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
# printing the stopwords in english

print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [ ]:
# data loding to pandas dataform

news_dataset = pd.read_csv('/content/FakeNewsNet.csv')
news_dataset.head()

,title,news_url,source_domain,tweet_num,real
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1

In [ ]:
# to get the shape of the dataset

news_dataset.shape

(23196, 5)

In [ ]:
# to get info of this data

news_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23196 entries, 0 to 23195
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          23196 non-null  object
 1   news_url       22866 non-null  object
 2   source_domain  22866 non-null  object
 3   tweet_num      23196 non-null  int64
 4   real           23196 non-null  int64
dtypes: int64(2), object(3)
memory usage: 906.2+ KB

In [ ]:
# to find is there any null values

news_dataset.isnull().sum()

title              0
news_url         330
source_domain    330
tweet_num          0
real               0
dtype: int64

In [ ]:
# replacing the null values with empty string

news_dataset = news_dataset.fillna('')

In [ ]:
#merging the news title and source_domine

news_dataset['content'] = news_dataset['title']+' '+news_dataset['source_domain']
news_dataset.head()

,title,news_url,source_domain,tweet_num,real,content
0,Kandi Burruss Explodes Over Rape Accusation on...,http://toofab.com/2017/05/08/real-housewives-a...,toofab.com,42,1,Kandi Burruss Explodes Over Rape Accusation on...
1,People's Choice Awards 2018: The best red carp...,https://www.today.com/style/see-people-s-choic...,www.today.com,0,1,People's Choice Awards 2018: The best red carp...
2,Sophia Bush Sends Sweet Birthday Message to 'O...,https://www.etonline.com/news/220806_sophia_bu...,www.etonline.com,63,1,Sophia Bush Sends Sweet Birthday Message to 'O...
3,Colombian singer Maluma sparks rumours of inap...,https://www.dailymail.co.uk/news/article-33655...,www.dailymail.co.uk,20,1,Colombian singer Maluma sparks rumours of inap...
4,Gossip Girl 10 Years Later: How Upper East Sid...,https://www.zerchoo.com/entertainment/gossip-g...,www.zerchoo.com,38,1,Gossip Girl 10 Years Later: How Upper East Sid...

In [ ]:
#seperating the content and label

x=news_dataset.drop(columns='real',axis=1)
y=news_dataset['real']

In [ ]:
# printing x and y
print(x)
print(y)

                                                   title  \
0      Kandi Burruss Explodes Over Rape Accusation on...
1      People's Choice Awards 2018: The best red carp...
2      Sophia Bush Sends Sweet Birthday Message to 'O...
3      Colombian singer Maluma sparks rumours of inap...
4      Gossip Girl 10 Years Later: How Upper East Sid...
...                                                  ...
23191  Pippa Middleton wedding: In case you missed it...
23192  Zayn Malik & Gigi Hadid’s Shocking Split: Why ...
23193  Jessica Chastain Recalls the Moment Her Mother...
23194  Tristan Thompson Feels "Dumped" After Khloé Ka...
23195  Kelly Clarkson Performs a Medley of Kendrick L...

                                                news_url  \
0      http://toofab.com/2017/05/08/real-housewives-a...
1      https://www.today.com/style/see-people-s-choic...
2      https://www.etonline.com/news/220806_sophia_bu...
3      https://www.dailymail.co.uk/news/article-33655...
4      https://www.zerchoo.com/entertainment/gossip-g...
...                                                  ...
23191  https://www.express.co.uk/news/royal/807049/pi...
23192  hollywoodlife.com/2018/03/13/zayn-malik-gigi-h...
23193  http://www.justjared.com/2018/01/17/jessica-ch...
23194  www.intouchweekly.com/posts/tristan-thompson-f...
23195  https://www.billboard.com/articles/news/bbma/8...

               source_domain  tweet_num  \
0                 toofab.com         42
1              www.today.com          0
2           www.etonline.com         63
3        www.dailymail.co.uk         20
4            www.zerchoo.com         38
...                      ...        ...
23191      www.express.co.uk         52
23192      hollywoodlife.com          7
23193      www.justjared.com         26
23194  www.intouchweekly.com         24
23195      www.billboard.com         85

                                                 content
0      Kandi Burruss Explodes Over Rape Accusation on...
1      People's Choice Awards 2018: The best red carp...
2      Sophia Bush Sends Sweet Birthday Message to 'O...
3      Colombian singer Maluma sparks rumours of inap...
4      Gossip Girl 10 Years Later: How Upper East Sid...
...                                                  ...
23191  Pippa Middleton wedding: In case you missed it...
23192  Zayn Malik & Gigi Hadid’s Shocking Split: Why ...
23193  Jessica Chastain Recalls the Moment Her Mother...
23194  Tristan Thompson Feels "Dumped" After Khloé Ka...
23195  Kelly Clarkson Performs a Medley of Kendrick L...

[23196 rows x 5 columns]
0        1
1        1
2        1
3        1
4        1
        ..
23191    1
23192    0
23193    1
23194    0
23195    1
Name: real, Length: 23196, dtype: int64

In [ ]:
# the steming segment

port_stem = PorterStemmer()
def stemming(content):
    stemmed_content = re.sub('[^a-zA-Z]',' ',content)
    stemmed_content = stemmed_content.lower()
    stemmed_content = stemmed_content.split()
    stemmed_content = [port_stem.stem(word) for word in stemmed_content if not word in stopwords.words('english')]
    stemmed_content =' '.join(stemmed_content)
    return stemmed_content

In [ ]:
news_dataset['content']=news_dataset['content'].apply(stemming)

In [ ]:
# printing the content column

print(news_dataset['content'])

0        kandi burruss explod rape accus real housew at...
1        peopl choic award best red carpet look www tod...
2        sophia bush send sweet birthday messag one tre...
3        colombian singer maluma spark rumour inappropr...
4        gossip girl year later upper east sider shock ...
                               ...
23191    pippa middleton wed case miss pippa marri lace...
23192    zayn malik gigi hadid shock split chanc reunit...
23193    jessica chastain recal moment mother boyfriend...
23194    tristan thompson feel dump khlo kardashian ref...
23195    kelli clarkson perform medley kendrick lamar h...
Name: content, Length: 23196, dtype: object

In [ ]:
# seperating the data and label

x=news_dataset['content'].values
y=news_dataset['real'].values

In [ ]:
# printing the x

print(x)

['kandi burruss explod rape accus real housew atlanta reunion video toofab com'
 'peopl choic award best red carpet look www today com'
 'sophia bush send sweet birthday messag one tree hill co star hilari burton breyton eva www etonlin com'
 ...
 'jessica chastain recal moment mother boyfriend slap kick genit www justjar com'
 'tristan thompson feel dump khlo kardashian refus let move la home exclus www intouchweekli com'
 'kelli clarkson perform medley kendrick lamar humbl hit billboard music award www billboard com']

In [ ]:
#printing the Y

print(y)

[1 1 1 ... 1 0 1]

In [ ]:
#conveting the textual data to numeric data

vectorizer=TfidfVectorizer()
vectorizer.fit(x)

x=vectorizer.transform(x)

In [ ]:
# spliting the test and train data

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=3)

In [ ]:
# model evulation

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC()
}

results = {}

for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    results[name] = accuracy_score(y_test, y_pred)

results

{'Logistic Regression': 0.8532505604414554,
 'Random Forest': 0.8556647697878945,
 'SVM': 0.8584238661838248}